# Data Manipulation with Pandas and NumPy 

Data manipulation is the process of changing, organizing, or transforming data to make it more useful, readable, and suitable for analysis. It involves taks like cleaning, filtering, sorting, grouping, or calculating new values from existing data. 

Tools like Pandas and NumPy, popular Python libraries, are often used to streamline these tasks. Pandas excels at handling structured data, like tables of crypto trades, for filtering or grouping, while NumPy supports fast numerical computations, such as calculating average prices or returns. 

For instance, a crypto investor might manipulate data by filtering trades to show only Bitcoin transactions over $5000, sorting them by timestamp to track price movements, and aggregating daily totals to assess trading volume. This helps uncover trends, optimize strategies, and ensures data accuracy, ultimately supporting better decisionsin the fast-paced crypto market.

### Pandas 

Pandas is a popular Python Library used for working with data. It helps you load, clean, analyze, and manipulate data easily. Think of it like an excel spreadsheet in Python! It's great for handling tables of data. 

Key Concepts: 

- Series: A single column of data (like a list of labels)

- Index: Labels for rows, helping you identify and access data

You can load data from files (CSV, Excel, e.t.c..), manipulate it, and save back. 

#### Installing/Importing pandas 

In [4]:
import pandas as pd 

## Create a DataFrame 

A dataframe is like a table with rows and columns. Let's create one with sample cryptocurrency data(e.g. coin names, prices, and trade volumes)

In [5]:
# Create a dictionary with crypto data 

data = {
    'Coin': ['Bitcoin', 'Ethereum', 'Ripple', 'Litecoin'],
    'Price': [120000, 3000, 0.85, 120],
    'Volume': [15000, 8000, 200000, 50000]
}

df = pd.DataFrame(data)

print(df)

       Coin      Price  Volume
0   Bitcoin  120000.00   15000
1  Ethereum    3000.00    8000
2    Ripple       0.85  200000
3  Litecoin     120.00   50000


#### Explore Data 

In [6]:
df

,Coin,Price,Volume
0,Bitcoin,120000.00,15000
1,Ethereum,3000.00,8000
2,Ripple,0.85,200000
3,Litecoin,120.00,50000


In [7]:
print(df.head(2))

       Coin     Price  Volume
0   Bitcoin  120000.0   15000
1  Ethereum    3000.0    8000


In [8]:
print(df.tail(2))

       Coin   Price  Volume
2    Ripple    0.85  200000
3  Litecoin  120.00   50000


In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Coin    4 non-null      object 
 1   Price   4 non-null      float64
 2   Volume  4 non-null      int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes
None


### Basic Data Manipulation 

In [10]:
# Select a specific column 

print(df[['Coin', 'Price']])

       Coin      Price
0   Bitcoin  120000.00
1  Ethereum    3000.00
2    Ripple       0.85
3  Litecoin     120.00


In [11]:
print(df['Coin'])

0     Bitcoin
1    Ethereum
2      Ripple
3    Litecoin
Name: Coin, dtype: object


### Filtering Rows

In [12]:
# Price greater than 

print(df[df['Price'] > 100])

       Coin     Price  Volume
0   Bitcoin  120000.0   15000
1  Ethereum    3000.0    8000
3  Litecoin     120.0   50000


### Sort Data 

Sort by a column like price in ascending or descending order 

In [13]:
print(df.sort_values('Price'))  # Sort by price in ascending order 

       Coin      Price  Volume
2    Ripple       0.85  200000
3  Litecoin     120.00   50000
1  Ethereum    3000.00    8000
0   Bitcoin  120000.00   15000


In [14]:
print(df.sort_values('Price', ascending=False))  # Sort in descending order 

       Coin      Price  Volume
0   Bitcoin  120000.00   15000
1  Ethereum    3000.00    8000
3  Litecoin     120.00   50000
2    Ripple       0.85  200000


### Add new column 

In [15]:
# What will be our price after 2% change? 

df['Price_after_2Pct'] = df['Price'] * 1.02
print(df)

       Coin      Price  Volume  Price_after_2Pct
0   Bitcoin  120000.00   15000        122400.000
1  Ethereum    3000.00    8000          3060.000
2    Ripple       0.85  200000             0.867
3  Litecoin     120.00   50000           122.400


In [16]:
df.describe()

,Price,Volume,Price_after_2Pct
count,4.000000,4.000000,4.000000
mean,30780.212500,68250.000000,31395.816750
std,59496.018003,89734.330108,60685.938363
min,0.850000,8000.000000,0.867000
25%,90.212500,13250.000000,92.016750
50%,1560.000000,32500.000000,1591.200000
75%,32250.000000,87500.000000,32895.000000
max,120000.000000,200000.000000,122400.000000


### Save and Load data with Pandas 

In [18]:
df.to_csv('crypto_data.csv', index=False)

## NumPy 

NumPy is a powerful python library for numerical computations, especially useful for working with arrays (list of numbers) and performing fast mathematical operations. It's a foundation for data manipulation, often used alongside Pandas, and is great for tasks like calculations, statistics, and handling crypto-related data. Below, i'll walk you through the basics step-by-step- installing NumPy, creating arrays, and performing common operations with simple code. 

#### Installing and Importing NumPy 

In [19]:
import numpy as np

#### Create a NumPy Array

A NumPy array is like a list, but optimized for math and faster operations. Let's create arrays with sample crypto data (e.g., coin prices and trade volumes)

In [21]:
prices = np.array([45000, 50000, 40000, 20000])
print(prices.shape)
print(prices)

(4,)
[45000 50000 40000 20000]


#### Data Type

In [22]:
print(prices.dtype)

int64


### Basic Data Manipulation 

In [ ]:
prices = np.array([45000, 50000, 40000, 20000])

prices_plus_1000 = prices + 1000        #Add 1000 to all prices 

print(prices_plus_1000)

[46000 51000 41000 21000]


In [26]:
# Compute for 2% increase in price 

price_s = np.array([46000, 51000, 41000, 21000])

price_increases = price_s * 1.02

print(price_increases)



[46920. 52020. 41820. 21420.]


In [27]:
# Filter data 

higher_price = price_s[price_s > 2000]
print(higher_price)

[46000 51000 41000 21000]


### Basic Statistical Functions 

In [28]:
volume = np.array([500000, 300000, 200000, 2500000])

print("\nStatistics for Volume")

print("Mean (Average): ", np.mean(volume))  # Average Volume 
print("Minimum: ", np.min(volume))  # Minimum Volume 
print("Maximum: ", np.max(volume))   # Maximum Volume 
print("Sum: ", np.sum(volume))   # Sum of Volume 
print("Standard Dev (Volatility): ", np.std(volume))   # Standard Dev (Volatility) of Volume 


Statistics for Volume
Mean (Average):  875000.0
Minimum:  200000
Maximum:  2500000
Sum:  3500000
Standard Dev (Volatility):  944391.3383762052


#### Working with a 2D array 

NumPy can handle multi-dimensional arrays. Let's combine our data into a 2D array (like a Table)

In [ ]:
# Create 2D Array

crypto_data = np.array([
    [45000, 5000],
    [30000, 28000],
    [11998, 8943]
])

print(crypto_data)

[[45000  5000]
 [30000 28000]
 [11998  8943]]


In [31]:
# Access a row 

crypto_data[2]

array([11998,  8943])

In [33]:
# Access Column 

crypto_data[:,0]

array([45000, 30000, 11998])